"""Initial migration

Revision ID: 6709f469d0d0
Revises: 
Create Date: 2025-09-11 17:11:59.530240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6709f469d0d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = 'staff'
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplanes',
    sa.Column('airplane_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('airplane_id')
    )
    op.create_table('staff_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GATE_MANAGER', 'CHECKIN_MANAGER', 'SUPERVISOR', name='staff_role_enum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_table('flights',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('flight_number', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELED', 'COMPLETED', name='flight_status_enum', native_enum=False), nullable=False),
    sa.Column('airplane_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.airplane_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_index(op.f('ix_flights_airplane_id'), 'flights', ['airplane_id'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index('uq_flight_number_departure', 'flights', ['flight_number', 'departure_time'], unique=True)
    op.create_table('ticket_shadows',
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('seat_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CHECKED_IN', 'BOARDED', 'CANCELED', 'DONE', name='ticket_status_enum', native_enum=False), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_number')
    )
    op.create_index(op.f('ix_ticket_shadows_flight_id'), 'ticket_shadows', ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_shadows_flight_id'), table_name='ticket_shadows')
    op.drop_table('ticket_shadows')
    op.drop_index('uq_flight_number_departure', table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_airplane_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_table('airplanes')
    # ### end Alembic commands ###
