services:

  seeder:
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    working_dir: /app
    depends_on:
      users_db:
        condition: service_healthy
      staff_db:
        condition: service_healthy
#    env_file:
#      - services/users_service/.env
#      - services/staff_service/.env
    environment:
      - PYTHONPATH=/app
      - USERS_DATABASE_URL=postgresql+asyncpg://postgres:postgres@users_db:5432/users_db
      - STAFF_DATABASE_URL=postgresql+asyncpg://postgres:postgres@staff_db:5432/staff_db
    volumes:
      - .:/app
    command: >
      sh -c "
        SQLALCHEMY_DATABASE_URL=$$USERS_DATABASE_URL alembic -c services/users_service/app/alembic.ini upgrade head &&
        SQLALCHEMY_DATABASE_URL=$$STAFF_DATABASE_URL alembic -c services/staff_service/app/alembic.ini upgrade head &&
        python -m scripts.cli seed --db all --flush --flights 60 --days 14
      "
    profiles: [ "dev" ]
    restart: "no"

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
    profiles: ["prod","dev","ci"]

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    profiles: ["prod","dev","ci"]

  users_db:
    image: postgres:16-alpine
    env_file: services/users_service/.env
    volumes:
      - users_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    profiles: ["prod","dev","ci"]

  staff_db:
    image: postgres:16-alpine
    env_file: services/staff_service/.env
    volumes:
      - staff_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    profiles: ["prod","dev","ci"]

  users:
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    depends_on:
      users_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file: services/users_service/.env
    environment:
      - PYTHONPATH=/app
    ports: ["8000:8000"]
    command: >
      sh -c "
        alembic -c services/users_service/app/alembic.ini upgrade head &&
        python -m services.users_service.app.main
      "
    profiles: ["prod"]

  staff:
    build:
      context: .
      dockerfile: services/staff_service/Dockerfile
    depends_on:
      staff_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file: services/staff_service/.env
    environment:
      - PYTHONPATH=/app
    ports: ["8002:8000"]
    command: >
      sh -c "
        alembic -c services/staff_service/app/alembic.ini upgrade head &&
        python -m services.staff_service.app.main
      "
    profiles: ["prod"]


  users-dev:
    working_dir: /app
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    depends_on:
      users_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file: services/users_service/.env
    environment:
      - PYTHONPATH=/app
    ports: ["8001:8000"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontends/customer/node_modules
    command: >
      sh -c "uvicorn services.users_service.app.main:app --host 0.0.0.0 --port 8000 --reload"
    profiles: ["dev"]

  staff-dev:
    working_dir: /app
    build:
      context: .
      dockerfile: services/staff_service/Dockerfile
    depends_on:
      staff_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file: services/staff_service/.env
    environment:
      - PYTHONPATH=/app
    ports: [ "8003:8000" ]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontends/staff/node_modules
    command: >
      sh -c "uvicorn services.staff_service.app.main:app --host 0.0.0.0 --port 8000 --reload"
    profiles: [ "dev" ]

  notifications_service:
    build:
      context: .
      dockerfile: notifications_service/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_started
    env_file: notifications_service/.env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672//
    command: celery -A notifications_service.app.worker worker --loglevel=INFO -Q emails
    profiles: [ "prod","dev" ]

  frontend-users:
    build:
      context: ./frontends/customer
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - users
    profiles: [ "prod" ]

  frontend-users-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontends/customer:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - users-dev
    profiles: [ "dev" ]

volumes:
  users_db_data:
  staff_db_data:
