"""init users schema

Revision ID: 48a6727cf744
Revises: 
Create Date: 2025-08-26 17:06:50.503160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a6727cf744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('discount_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('percent_off', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('discount_code')
    )
    op.create_table('flights_ref',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('flight_number', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELED', 'COMPLETED', name='flight_status_enum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('flight_id'),
    sa.UniqueConstraint('flight_number', 'departure_time', name='uq_flightref_number_departure')
    )
    op.create_index('ix_flightref_o_d_dt', 'flights_ref', ['origin', 'destination', 'departure_time'], unique=False)
    op.create_index(op.f('ix_flights_ref_flight_number'), 'flights_ref', ['flight_number'], unique=False)
    op.create_table('options',
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('option_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seat_types',
    sa.Column('type_name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('type_name')
    )
    op.create_table('user_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', name='role_enum', native_enum=False), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'PAID', 'CANCELED', 'REFUNDED', name='booking_status_enum', native_enum=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discount_code', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['discount_code'], ['discounts.discount_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_discount_code'), 'bookings', ['discount_code'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('passengers',
    sa.Column('passenger_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_accounts.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_index(op.f('ix_passengers_owner_id'), 'passengers', ['owner_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('BOOKED', 'CHECKED_IN', 'BOARDED', 'CANCELED', 'DONE', name='ticket_status_enum', native_enum=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('passenger_id', sa.Uuid(), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('seat_type_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights_ref.flight_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.passenger_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_type_name'], ['seat_types.type_name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_number')
    )
    op.create_index('ix_ticket_booking', 'tickets', ['booking_id'], unique=False)
    op.create_index('ix_ticket_flight', 'tickets', ['flight_id'], unique=False)
    op.create_index('ix_ticket_passenger', 'tickets', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_tickets_booking_id'), 'tickets', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tickets_flight_id'), 'tickets', ['flight_id'], unique=False)
    op.create_index(op.f('ix_tickets_passenger_id'), 'tickets', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_tickets_seat_type_name'), 'tickets', ['seat_type_name'], unique=False)
    op.create_table('ticket_options',
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.option_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.ticket_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_number', 'option_id'),
    sa.UniqueConstraint('ticket_number', 'option_id', name='uq_ticket_option')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_options')
    op.drop_index(op.f('ix_tickets_seat_type_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_passenger_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_flight_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_booking_id'), table_name='tickets')
    op.drop_index('ix_ticket_passenger', table_name='tickets')
    op.drop_index('ix_ticket_flight', table_name='tickets')
    op.drop_index('ix_ticket_booking', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_passengers_owner_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_discount_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_table('seat_types')
    op.drop_table('options')
    op.drop_index(op.f('ix_flights_ref_flight_number'), table_name='flights_ref')
    op.drop_index('ix_flightref_o_d_dt', table_name='flights_ref')
    op.drop_table('flights_ref')
    op.drop_table('discounts')
    # ### end Alembic commands ###
