"""added stripe

Revision ID: 52b2c7c42e49
Revises: fcf20c69e813
Create Date: 2025-08-30 17:57:39.207919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b2c7c42e49'
down_revision: Union[str, Sequence[str], None] = 'fcf20c69e813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True))
    op.add_column('bookings', sa.Column('stripe_payment_status', sa.String(length=32), nullable=True))
    op.add_column('bookings', sa.Column('stripe_charge_id', sa.String(length=128), nullable=True))
    op.add_column('bookings', sa.Column('stripe_refund_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_bookings_stripe_payment_intent_id'), 'bookings', ['stripe_payment_intent_id'], unique=True)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_stripe_payment_intent_id'), table_name='bookings')
    op.drop_column('bookings', 'stripe_refund_id')
    op.drop_column('bookings', 'stripe_charge_id')
    op.drop_column('bookings', 'stripe_payment_status')
    op.drop_column('bookings', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
