"""pricing and seat type

Revision ID: fcf20c69e813
Revises: 48a6727cf744
Create Date: 2025-08-29 13:48:19.978902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf20c69e813'
down_revision: Union[str, Sequence[str], None] = '48a6727cf744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _constraint_exists(conn, table: str, name: str) -> bool:
    res = conn.execute(sa.text("""
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        WHERE t.relname = :table AND c.conname = :name
        LIMIT 1
    """), {"table": table, "name": name})
    return res.scalar() is not None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.create_table('pricing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seat_types', sa.Column('multiplier', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False))
    if not _constraint_exists(bind, "ticket_options", "uq_ticket_option"):
        op.create_unique_constraint(
            "uq_ticket_option",
            "ticket_options",
            ["ticket_number", "option_id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if _constraint_exists(bind, "ticket_options", "uq_ticket_option"):
        op.drop_constraint("uq_ticket_option", "ticket_options", type_="unique")
    op.drop_column('seat_types', 'multiplier')
    op.drop_table('pricing_config')
    # ### end Alembic commands ###
