import random
import string
import datetime as dt
from typing import Iterable


RNG = random.Random()


def pick(seq: Iterable[str]) -> str:
    """
    Randomly selects an item from the given iterable sequence of strings. The sequence is internally converted to a list,
    and an item is picked based on a random index generated within the bounds of its length.

    :param seq: An iterable sequence of strings from which a random string is selected.
    :type seq: Iterable[str]
    :return: A randomly selected string from the supplied sequence.
    :rtype: str
    """
    seq = list(seq)
    return seq[RNG.randrange(0, len(seq))]


AIRPORTS = [
    "KBP",
    "ODS",
    "LWO",
    "IEV",
    "DNK",
    "WAW",
    "KRK",
    "GDN",
    "BER",
    "MUC",
    "FRA",
    "VIE",
    "ZRH",
    "CDG",
    "AMS",
]

CARRIERS = ["FA", "FX"]


def flight_number() -> str:
    """
    Generates a flight number combining a random airline carrier code and a
    random number sequence. The carrier code is chosen from a predefined
    list, and the number sequence is a four-digit integer padded with zeros
    if necessary.

    :return: A string representing a flight number in the format of
        a carrier code followed by a padded four-digit number.
    :rtype: str
    """
    return f"{pick(CARRIERS)}{RNG.randrange(10, 9999):04d}"


def rand_datetime_within_days(days: int) -> tuple[dt.datetime, dt.datetime]:
    """
    Generates two random datetime objects within a specified range of days from
    the current time, representing a departure and arrival time. The departure
    time is generated with a random time within a day and the arrival time is
    generated by adding a random duration to the departure time.

    :param days: The range of days in both directions (past and future) from
                 the current date within which the random datetime objects
                 should be generated.
    :type days: int
    :return: A tuple containing two datetime objects: the departure time and
             the arrival time.
    :rtype: tuple[dt.datetime, dt.datetime]
    """
    now = dt.datetime.now(dt.timezone.utc)
    delta_days = RNG.randint(-days, days)
    dep = (now + dt.timedelta(days=delta_days)).replace(
        hour=RNG.randint(6, 22),
        minute=RNG.choice([0, 15, 30, 45]),
        second=0,
        microsecond=0,
    )
    dur_hours = RNG.randint(1, 4)
    arr = dep + dt.timedelta(hours=dur_hours, minutes=RNG.choice([0, 15, 30]))
    return dep, arr


def code(n: int = 8) -> str:
    """
    Generates a random alphanumeric string of uppercase letters and digits with
    a specified length.

    This function creates a string consisting of random uppercase letters and
    digits. The length of the generated string is determined by the input
    parameter. The characters are chosen uniformly at random to ensure an equal
    distribution of probabilities.

    :param n: Length of the generated alphanumeric string. Defaults to 8 if not
        provided.
    :type n: int
    :return: A random alphanumeric string of the specified length.
    :rtype: str
    """
    alphabet = string.ascii_uppercase + string.digits
    return "".join(RNG.choice(alphabet) for _ in range(n))
